name: tests

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop
    workflow_call: {}

jobs:
    tests: 
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                cdd_gmp: [true, false]
                python: ['3.10', '3.14']
                extra: [base, cdd, extra, full]

                exclude:
                    - python: '3.10'
                    - extra: cdd
                    - extra: extra
                    - os: ubuntu-latest
                      cdd_gmp: true
                      extra: base
                    - os: ubuntu-latest
                      cdd_gmp: false
                      extra: full
                    - os: macos-latest
                      cdd_gmp: true
                      extra: base
                    - os: macos-latest
                      cdd_gmp: false
                      extra: full
                    - os: windows-latest
                      cdd_gmp: true
                      extra: base
                    - os: windows-latest
                      cdd_gmp: false
                      extra: full

        runs-on: ${{ matrix.os }}

        if: "!contains(github.event.head_commit.message, '[skip tests]')"

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python }}

            - name: Install system dependencies
              if: matrix.cdd_gmp
              run: |
                if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
                    sudo apt-get update
                    sudo apt-get install -y libcdd-dev libgmp-dev
                elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
                    brew install cddlib gmp
                elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
                    choco install cddlib gmp
                fi

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                python -m pip install tox tox-gh-actions

            - name: Tests with tox
              run: |
                if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
                  export CFLAGS="-I/opt/homebrew/include"
                  export LDFLAGS="-L/opt/homebrew/lib"
                  export PKG_CONFIG_PATH="/opt/homebrew/lib/pkgconfig:${PKG_CONFIG_PATH}"
                fi
                tox -e ${{ matrix.extra }}